### ISSUE TITLE
osx compile instructions

### ISSUE THREAD

**Issue by Daandelange** [d3cod3/ofxOpenDHT#1]
Hey, I tried the build-from-source instructions from the link in the readme but there were some issues on osx.
 - 2 missing brew dependencies: `fmt` and `cppunit`
 - Also I think it doesn't build the library as shared.
 - I stopped because of incrementing errors.

Easier solution: `brew install opendht`.
Maybe you could add that to the readme ?

**Comment by d3cod3** [comment]
Right, i've compiled it on my mac machine a long time ago, and there was no issues, but i'll add it to the readme, of course!

So with ```brew install opendht``` is compiling the addon ok? Because if you check the addon_config.mk, it needs to link opendht, gnutls, nettle and fmt libs.

So maybe the right call would be to add:

```brew install fmt cppunit nettle gnutls msgpack-cxx argon2 asio opendht```

no?

**Comment by Daandelange** [comment]
`brew install opendht` [also installs the above mentioned dependencies](https://formulae.brew.sh/formula/opendht), imo it's better to let the bottle define the dependencies.
But wait, in fact brew builds and installs the c-library, not the c++ library... so it doesn't work with ofxOpenDHT.

I got the standalone build script working after `brew install opendht` (which installed missing deps), but it doesn't link due to osx (10.15) refusing to install into `/usr/lib/opendth.xxxx.dylib`. Even with `sudo brew link opendht`. So that's not an option too.

With brew I edited the formulae locally switching to `-DOPENDHT_C=OFF`, then it installs correctly, but then `#include <opendht.h> doesn't work, it needs a custom include search path (`/usr/local/lib`) in Qt-Creator, so not an out-of-the box solution too.

Is opendht a new requirement for ofxVP or is it just for an object/node ?

**Comment by d3cod3** [comment]
It's needed for Mosaic, not ofxVP, it's for the internal distributed chatroom.
Anyway, i cheked it on my mac and i have it working first with brew:

```brew install fmt cppunit nettle gnutls msgpack-cxx argon2 asio```

and then compiling libopendht as explained [here](https://github.com/savoirfairelinux/opendht/wiki/Build-the-library):

```
# clone the repo
git clone https://github.com/savoirfairelinux/opendht.git

# build and install
cd opendht
mkdir build && cd build
cmake -DOPENDHT_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
make -j4
sudo make install
```

release 0.6.9 already has it included, you'll find the dynamic lib inside the Mosaic.app, with all the other libraries needed, plus in the fixDynamicLibs_*.sh scripts you'll find all the needed fixes for the libs paths.

That should work, but depending on your macOS version it could appear some issue, i installed and compiled it with no problems on macOS 11.4 ( Big Sur )

**Comment by d3cod3** [comment]
Compiling from opendht github repo will let you install the library in ```/usr/lib/libopendht.xxx..dylib```, so addon compile will run afterward

**Comment by Daandelange** [comment]
That's exactly the issue... here's what I get, I'll try to find a proper way for this ;)
I guess binary distributions are also affected, as Mosaic compiles with the system headers and needs a global install. (?)

````
-- Installing: /usr/lib/libopendht.3.2.0.dylib
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/.../opendht/build/libopendht.3.2.0.dylib" to
  "/usr/lib/libopendht.3.2.0.dylib": Operation not permitted.
  ````

**Comment by d3cod3** [comment]
even with ```sudo make install``` ? ( that's strange, maybe some security mechanism from macOS? )


And yes, it needs a global install with the heders, plus the dynamic lib.

And no, binaries are working, i've tested on macs with no developer stuff installed, Mosaic with opendht chatroom ( 0.6.9 ) is working from the binary, no issue.

**Comment by Daandelange** [comment]
Yes, also with `sudo make install` but I found the issue : I was building from `~/code/opendht` which is in user space, which obviously cannot symlink to system space. New apple's new security features.
Compiling from `/Volumes/ExternalDisk/Projects/opendht` is fine !

This code below at least shows a warning when running from user space.

```` bash
# ...opendht compilation code...
echo `pwd` | grep -Eq "^`realpath ~/../`" && echo "You are running from user space, newer versions of macos (±10.15+) will probably fail to install (below). Please copy the compilation files out of your user folder."
sudo make install
````

**Comment by d3cod3** [comment]
Good to know it's solved, i'll add your caveat to the readme!

Apple it's like a game where every step some door is closing, probably, to win the game, one just need to stay still, in the same place, forever

**Comment by d3cod3** [comment]
Solved with https://github.com/d3cod3/ofxOpenDHT/commit/2b23d8d29b3ac122d6819475c7f250b409f530f1

**Comment by Daandelange** [comment]
XCode also doesn't run out of the box. Changes to the project after PG nightly: 
- `Project C Flags: -DMSGPACK_NO_BOOST`
- `Library Search Paths: /usr/local/lib/` (if using used default install location, otherwise `/usr/lib`)

**Comment by Daandelange** [comment]
I don't know why, it didn't work anymore in Qt-Creator.
Here's a correction to the `.qbs` file I made to fix:
````qbs
// In the example, remove any properties from the `.qbs`.

// Linux + openDHT support
Properties {
    condition: qbs.targetOS.contains("linux")
    of.pkgConfigs: outer.concat(["/usr/local/lib/pkgconfig/opendht.pc"])
}

// OSX + openDHT support
Properties {
    condition: qbs.targetOS.contains("osx") || qbs.targetOS.contains("macos")
    of.dynamicLibraries: outer.concat(['opendht'])
    // libraryPaths seems to break runtime after compilation, and it works without them.
    //cpp.libraryPaths: outer.concat([
    //    '/usr/local/lib/',
    //])
    cpp.systemIncludePaths: outer.concat([
        '/usr/local/include/',
    ])
    // Seems not neccessary, probably injected via addon_config.mk qbs parsing ?
    //of.linkerFlags: outer.concat(['-lgnutls', '-lnettle', '-lfmt',]) // '-lopendht' already added by dynamicLibraries
    //of.cxxFlags: outer.concat(['-DMSGPACK_NO_BOOST'])
}
````
